import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LanguagueSelection from '../components/LanguagueSelection'

export default function Home(props) {
  const { index } = props
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LanguagueSelection />
        <h1 className={styles.title}>{index.tittle}</h1>
      </main>
    </div>
  )
}
export async function getStaticProps({ locale }) {
  // const response = await fetch("URL")
  // const result = await response.json()
  const response = await import(`../lang/${locale}.json`)
  return {
    props: {
      index: response.default.index,
    },
  }
}
